doc: add error argument to quicendpoint.destroy
Currently, the following error is generated by the test-doc target:

Error: Invalid param "error"
 > null
 > quicendpoint.destroy([error])
    at /node_quic/tools/doc/json.js:352:17
    at Array.forEach (<anonymous>)
    at parseSignature (/node_quic/tools/doc/json.js:299:13)
    at doSection (/node_quic/tools/doc/json.js:145:11)
    at doSection (/node_quic/tools/doc/json.js:200:9)
    at doSection (/node_quic/tools/doc/json.js:200:9)
    at doSection (/node_quic/tools/doc/json.js:200:9)
    at /node_quic/tools/doc/json.js:58:7
make[2]: *** [out/doc/api/quic.html] Error 1
make[1]: *** [doc-only] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [test] Error 2

This commit adds the missing parameter to the documentation.

PR-URL: https://github.com/nodejs/quic/pull/277
Reviewed-By: James M Snell <jasnell@gmail.com>